### PR TITLE
Convert the client app into a library

### PR DESCRIPTION
**Pull request by RodolfoSilva**
I moved all things related to the final application to the example folder, this will allow custom implementation without cloning the client repository.

### CODE REVIEW

**Comment by alex-min** [comment]
I think I'm okay with that but we need to fix the tests

**Comment by RodolfoSilva** [comment]
@alex-min I think you will need to regenerate all images, the test error variance is less than 0.0%. I think this is related to a change in flutter version or material.

**Comment by alex-min** [comment]
Will do tomorrow

**Comment by RodolfoSilva** [comment]
> @alex-min I think you will need to regenerate all images, the test error variance is less than 0.0%. I think this is related to a change in flutter version or material.

Forget it, I found the problem. The pubspec.yaml library was missing the configuration: `uses-material-design: true`
It seems this option is responsible for loading all material icons.

Once again, the test suite saves the day. 😂

**Pull request merged**
