### PR TITLE
Allow registry widgets and execs

### PR DESCRIPTION
**Pull request by RodolfoSilva**
I think with these two registries we can allow the user to define new widgets and execs. Maybe with this implementation we can split the library into two parts: one just with the parser and interaction with the server, and another for the widgets and execs.

I thinks this could solve the issue: #1

### CODE REVIEW

**Review by alex-min — COMMENTED** [review]
I'm okay with that, i'll just check tomorrow if the tests are still working.

I'll setup some github action but for now the tests have to be run manually

**Comment by RodolfoSilva** [comment]
Ok. Thanks :D

**Comment by alex-min** [comment]
No worries, I've been writing tests pretty extensively on this project to make sure everything is stable

**Comment by RodolfoSilva** [comment]
@alex-min the test check fails becouse, seams I dont have enought permissions to execute actions that can commint on issues. But the test check pass, only the analyzer, formatter and issue comment, fails. I thinks this could be solved in another PR.

I've created another PR to solve the CI issues: #5

**Pull request merged**
